# Generated by Django 5.0.1 on 2024-01-16 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Serviec',
            new_name='Service',
        ),
    ]
